--- #YAML:1.0
name:                WebService-EditDNS
version:             0.11
abstract:            Perl interface to EditDNS API
license:             ~
author:              
    - Michal Wojciechowski <odyniec@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
